# AI Math Prep Crash Course

## Week 1
### 01 - Equations and functions
Playlist: [Khan Academy Linear equations and functions](https://www.youtube.com/playlist?list=PLSQl0a2vh4HD5FU2_A5sJvEflEZ6fq6dC)
- [ ] [Graphing proportional relationships example # 8th grade # Khan Academy.mp4](https://www.youtube.com/watch?v=1F7LAJEVp-U)
- [ ] [Similar triangles to prove that the slope is constant for a line # Algebra I # Khan Academy.mp4](https://www.youtube.com/watch?v=24WMbh1BBKc)
- [ ] [Slope-intercept form from table # Linear equations and functions # 8th grade # Khan Academy.mp4](https://www.youtube.com/watch?v=3Ayt7mOd_To)
- [ ] [Testing if a relationship is a function # Functions and their graphs # Algebra II # Khan Academy.mp4](https://www.youtube.com/watch?v=3SO1BQQ9_1E)
- [ ] [x- and y-intercepts 2 # Linear equations and functions # 8th grade # Khan Academy.mp4](https://www.youtube.com/watch?v=405boztgZig)
- [ ] [Recognize functions from tables # Functions and their graphs # Algebra II # Khan Academy.mp4](https://www.youtube.com/watch?v=5EdbPz1ZVn0)
- [ ] [Intuitive understanding of slope example # Algebra I # Khan Academy.mp4](https://www.youtube.com/watch?v=5cK86VKoBPw)
- [ ] [Slope of a line# negative slope # Graphing lines and slope # Algebra Basics # Khan Academy.mp4](https://www.youtube.com/watch?v=5fkh01mClLU)
- [ ] [Graphing solutions to two-variable linear equations example 1 # Algebra I # Khan Academy.mp4](https://www.youtube.com/watch?v=6_9xNMtwnfs)
- [ ] [Recognizing linear functions # Linear equations and functions # 8th grade # Khan Academy.mp4](https://www.youtube.com/watch?v=81SseQCpGws)
- [ ] [Slope-intercept equation from slope and point # Algebra I # Khan Academy.mp4](https://www.youtube.com/watch?v=86NwKBcOlow)
- [ ] [Solving for F in terms of C # Linear equations # Algebra I # Khan Academy.mp4](https://www.youtube.com/watch?v=9wOalujeZf4)
- [ ] [Slope from two ordered pairs example 2 # Algebra I # Khan Academy.mp4](https://www.youtube.com/watch?v=AqFwKecNaTk)
- [ ] [Finding intercepts from a table # Algebra I # Khan Academy.mp4](https://www.youtube.com/watch?v=BR5yFOt0zao)
- [ ] [Representing and comparing rates # Linear equations and functions # 8th grade # Khan Academy.mp4](https://www.youtube.com/watch?v=CFSHq099Mx0)
- [ ] [Linear and nonlinear functions (example 3) # 8th grade # Khan Academy.mp4](https://www.youtube.com/watch?v=CGZZINHT0I8)
- [ ] [Function notation in context example # Functions and their graphs # Algebra II # Khan Academy.mp4](https://www.youtube.com/watch?v=F6rtQczAYco)
- [ ] [Evaluating functions given their formula # Functions and their graphs # Algebra II # Khan Academy.mp4](https://www.youtube.com/watch?v=HUnF0mZmMKc)
- [ ] [Graphing proportional relationships example 3 # 8th grade # Khan Academy.mp4](https://www.youtube.com/watch?v=IXRMVcoqRRQ)
- [ ] [Introduction to the coordinate plane # Introduction to algebra # Algebra I # Khan Academy.mp4](https://www.youtube.com/watch?v=Id6o6CE4WvE)
- [ ] [Linear and nonlinear functions (example 2) # 8th grade # Khan Academy.mp4](https://www.youtube.com/watch?v=LoKEPEPaNm4)
- [ ] [Linear and nonlinear functions (example 1) # 8th grade # Khan Academy.mp4](https://www.youtube.com/watch?v=MKErxh58RME)
- [ ] [Recognizing functions (example 4) # Functions and their graphs # Algebra II # Khan Academy.mp4](https://www.youtube.com/watch?v=N4nrdf0yYfM)
- [ ] [Comparing linear functions 3 # Algebra I # Khan Academy.mp4](https://www.youtube.com/watch?v=NOsnG2DkGKM)
- [ ] [Graphing proportional relationships example 2 # 8th grade # Khan Academy.mp4](https://www.youtube.com/watch?v=OWPVZoxNe-U)
- [ ] [Finding the slope of a line from its graph # Algebra I # Khan Academy.mp4](https://www.youtube.com/watch?v=OhUkMQtBGmE)
- [ ] [Relations and functions # Functions and their graphs # Algebra II # Khan Academy.mp4](https://www.youtube.com/watch?v=Pt-Tn6L60-o)
- [ ] [Converting linear equations to slope-intercept form # 8th grade # Khan Academy.mp4](https://www.youtube.com/watch?v=QWLc4xQ3S3o)
- [ ] [Coordinate plane examples # Linear equations and functions # 8th grade # Khan Academy.mp4](https://www.youtube.com/watch?v=Pt-Tn6L60-o)
- [ ] [Testing solutions to linear equations # Graphing lines and slope # Algebra Basics # Khan Academy.mp4](https://www.youtube.com/watch?v=QWLc4xQ3S3o)
- [ ] [Slope from two ordered pairs example 1 # Algebra I # Khan Academy.mp4](https://www.youtube.com/watch?v=R948Tsyq4vA)
- [ ] [Slope-intercept equation from two solutions example # Algebra I # Khan Academy.mp4](https://www.youtube.com/watch?v=32xA_WPS7OM)
- [ ] [Interpreting a graph exercise example # Linear equations and functions # 8th grade # Khan Academy.mp4](https://www.youtube.com/watch?v=Uz0MtFlLD-k)
- [ ] [Does a vertical line represent a function# # Functions and their graphs # Algebra II # Khan Academy.mp4](https://www.youtube.com/watch?v=VhNkWdLGpmA)
- [ ] [Comparing linear functions 1 # Algebra I # Khan Academy.mp4](https://www.youtube.com/watch?v=W84lObmOp8M)
- [ ] [Functions as graphs # Functions and their graphs # Algebra II # Khan Academy.mp4](https://www.youtube.com/watch?v=wSiamij_i_k)
- [ ] [Comparing rates # Linear equations and functions # 8th grade # Khan Academy.mp4](https://www.youtube.com/watch?v=aeyFb2eVH1c)
- [ ] [What is a function# # Functions and their graphs # Algebra II # Khan Academy.mp4](https://www.youtube.com/watch?v=BZxZ_eEuJBM)
- [ ] [Evaluating functions given their graph # Functions and their graphs # Algebra II # Khan Academy.mp4](https://www.youtube.com/watch?v=A6JdlY52NFg)
- [ ] [Difference between equations and functions # Functions and their graphs # Algebra II # Khan Academy.mp4](https://www.youtube.com/watch?v=lEhf75ma7Ww)
- [ ] [Recognizing functions (example 3) # Functions and their graphs # Algebra II # Khan Academy.mp4](https://www.youtube.com/watch?v=qGmJ4F3b5W8)
- [ ] [Linear function example# spending money # Linear equations and functions # 8th grade # Khan Academy.mp4](https://www.youtube.com/watch?v=qGmJ4F3b5W8)
- [ ] [Graphical relations and functions # Functions and their graphs # Algebra II # Khan Academy.mp4](https://www.youtube.com/watch?v=57BiI_iD3-U)
- [ ] [Modeling with linear equations example 1 # Linear equations and functions # 8th grade # Khan Academy.mp4](https://www.youtube.com/watch?v=IReD6c_njOY)
- [ ] [Graphs of linear equations # Linear equations and functions # 8th grade # Khan Academy.mp4](https://www.youtube.com/watch?v=W84lObmOp8M)
- [ ] [Graph from slope-intercept equation example # Algebra I # Khan Academy.mp4](https://www.youtube.com/watch?v=uk7gS3cZVp4)
- [ ] [Comparing linear functions 2 # Algebra I # Khan Academy.mp4](https://www.youtube.com/watch?v=wl2iQAuQl7Y)
- [ ] [Finding intercepts from an equation # Algebra I # Khan Academy.mp4](https://www.youtube.com/watch?v=xGmef7lFc5w)
- [ ] [Finding the x-intercept of a line # Algebra I # Khan Academy.mp4](https://www.youtube.com/watch?v=xR9r38mZjK4)

### 02 - Graphing and transformations
Playlist: [Khan Academy Precalculus](https://www.youtube.com/playlist?list=PLE88E3C9C7791BD2D)
- [ ] [Function inverses example 2 # Functions and their graphs # Algebra II # Khan Academy.mp4](https://www.youtube.com/watch?v=8lfXWE1rLFs)

### 03 - Trigonometry review
Playlist: [Khan Academy Trigonometry](https://www.youtube.com/playlist?list=PLD6DA74C1DBF770E7)
- [ ] [Basic trigonometry # Basic trigonometry # Trigonometry # Khan Academy.mp4](https://www.youtube.com/watch?v=Jsiy4TxgIME)
- [ ] [Basic trigonometry II # Basic trigonometry # Trigonometry # Khan Academy.mp4](https://www.youtube.com/watch?v=G-T_6hCdMQc)
- [ ] [Radian and degree # Unit circle definition of trig functions # Trigonometry # Khan Academy.mp4](https://www.youtube.com/watch?v=9zspW8u6kQM)
- [ ] [Using Trig Functions.mp4](https://www.youtube.com/watch?v=znR9tW4AiZI)
- [ ] [Using Trig Functions Part II.mp4](https://www.youtube.com/watch?v=RoXmKYjpLGk)
- [ ] [The unit circle definition of trigonometric function.mp4](https://www.youtube.com/watch?v=6Qv_bPlQS8E)
- [ ] [Unit Circle Definition of Trig Functions.mp4](https://www.youtube.com/watch?v=ZWSoyUxAQW0)
- [ ] [Graph of the sine function.mp4](https://www.youtube.com/watch?v=2zoiW4PdVKo)
- [ ] [Graphs of trig functions.mp4](https://www.youtube.com/watch?v=QmxMpPkZpME)
- [ ] [Graphing trig functions.mp4](https://www.youtube.com/watch?v=vHYI93UV5Kg)
- [ ] [More trig graphs.mp4](https://www.youtube.com/watch?v=NIG3l8oWKYE)
- [ ] [Determining the equation of a trigonometric function.mp4](https://www.youtube.com/watch?v=yvW5l9W1hgE)
- [ ] [Trigonometric Identities.mp4](https://www.youtube.com/watch=v=OLzXqIqZZz0)
- [ ] [Proof# sin(a+b)  = (cos a)(sin b) + (sin a)(cos b).mp4](https://www.youtube.com/watch?v=zw0waJCEc-w)
- [ ] [Proof# cos(a+b) = (cos a)(cos b)-(sin a)(sin b).mp4](https://www.youtube.com/watch?v=V3-xCPDzQ1Q)
- [ ] [Trig identities part 2 (part 4 if you watch the proofs) # Trigonometry # Khan Academy.mp4](https://www.youtube.com/watch?v=ZWSoyUxAQW0)
- [ ] [Trig identities part 3 (part 5 if you watch the proofs) # Trigonometry # Khan Academy.mp4](https://www.youtube.com/watch?v=du5lLkNj1Pc)
- [ ] [Inverse trig functions# arcsin # Trigonometry # Khan Academy.mp4](https://www.youtube.com/watch=v=6lrN4nF2zlk)
- [ ] [Inverse trig functions# arctan # Trigonometry # Khan Academy.mp4](https://www.youtube.com/watch=v=7cJNYTnhUI0)
- [ ] [Inverse trig functions# arccos # Trigonometry # Khan Academy.mp4](https://www.youtube.com/watch=v=7cJNYTnhUI0)
- [ ] [Trigonometry identity review-fun # Trig identities and examples # Trigonometry # Khan Academy.mp4](https://www.youtube.com/watch?v=6lrN4nF2zlk)

### 04 - Introduction to sequences and summation
Playlist: [Khan Academy Sequences series and induction precalculus](https://www.youtube.com/playlist?list=PLSQl0a2vh4HC8Tnp8lgLieZ3_PlMnV1ii)
- [ ] [Alternate proof to induction for integer sum # Precalculus # Khan Academy.mp4](https://www.youtube.com/watch?v=1wnIsgUivEQ)
- [ ] [Repeating decimal as infinite geometric series # Precalculus # Khan Academy.mp4](https://www.youtube.com/watch=v=2BgWWsypzLA)
- [ ] [Sigma notation for sums # Sequences, series and induction # Precalculus # Khan Academy.mp4](https://www.youtube.com/watch?v=5jwXThH6fg4)
- [ ] [Series sum example # Sequences, series and induction # Precalculus # Khan Academy.mp4](https://www.youtube.com/watch=v=A6fbDssPeac)
- [ ] [Finding the 100th term in a sequence # Sequences, series and induction # Precalculus # Khan Academy.mp4](https://www.youtube.com/watch=v=C5titprQAc4)
- [ ] [Geometric series # Sequences, series and induction # Precalculus # Khan Academy.mp4](https://www.youtube.com/watch=v=CecgFWTg9pQ)
- [ ] [Converting an explicit formula of a geometric sequence to a recursive formula # Khan Academy.mp4](https://www.youtube.com/watch?v=5qiyxgJ6lzM)
- [ ] [Geometric series convergence and divergence examples # Precalculus # Khan Academy.mp4](https://www.youtube.com/watch=v=8Xl3jwsjacI)
- [ ] [Explicit and recursive definitions of sequences # Precalculus # Khan Academy.mp4](https://www.youtube.com/watch=v=9ZJ48VLyrzQ)
- [ ] [Equations of sequence patterns # Sequences, series and induction # Precalculus # Khan Academy.mp4](https://www.youtube.com/watch=v=8XL3jwsjacI)
- [ ] [Introduction to arithmetic sequences # Sequences, series and induction # Precalculus # Khan Academy.mp4](https://www.youtube.com/watch=v=9ZJ48VLyrzQ)
- [ ] [Constructing a geometric series for new users # Precalculus # Khan Academy.mp4](https://www.youtube.com/watch=v=8XL3jwsjacI)
- [ ] [Sum of an infinite geometric series # Sequences, series and induction # Precalculus # Khan Academy.mp4](https://www.youtube.com/watch?v=wjYnzkAhcNk)
- [ ] [Geometric sequences # Sequences, series and induction # Precalculus # Khan Academy.mp4](https://www.youtube.com/watch=v=dIGLhLMsy2U)
- [ ] [Formula for a finite geometric series # Sequences, series and induction # Precalculus # Khan Academy.mp4](https://www.youtube.com/watch?v=H4Zc4F9neAs)
- [ ] [Deductive reasoning 3 # Sequences, series and induction # Precalculus # Khan Academy.mp4](https://www.youtube.com/watch?v=dtg2Jv6Vs_E)
- [ ] [Introduction to geometric sequences # Sequences, series and induction # Precalculus # Khan Academy.mp4](https://www.youtube.com/watch=v=pXo0bG4iAyg)
- [ ] [Inductive reasoning 3 # Sequences, series and induction # Precalculus # Khan Academy.mp4](https://www.youtube.com/watch=v=0XJ_1J6E9tk)
- [ ] [Series as sum of sequence # Sequences, series and induction # Precalculus # Khan Academy.mp4](https://www.youtube.com/watch=v=BfxSlFm8vDE)
- [ ] [Proof by induction # Sequences, series and induction # Precalculus # Khan Academy.mp4](https://www.youtube.com/watch=v=wblW_M_HVQ8)
- [ ] [Another derivation of the sum of an infinite geometric series # Precalculus # Khan Academy.mp4](https://www.youtube.com/watch=v=qpj27dTeE4A)

## Week 2
### 01 - Vectors
Playlist: [3Blue1Brown Essence of linear algebra](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab)
- [ ] [Vectors # Chapter 1, Essence of linear algebra.mp4](https://www.youtube.com/watch?v=fNk_zzaMoSs)
- [ ] [Linear combinations, span, and basis vectors ｜ Chapter 2, Essence of linear algebra.mp4](https://www.youtube.com/watch?v=k7RM-ot2NWY)
- [ ] [Linear transformations and matrices ｜ Chapter 3, Essence of linear algebra.mp4](https://www.youtube.com/watch?v=kYB8IZa5AuE)
- [ ] [Matrix multiplication as composition ｜ Chapter 4, Essence of linear algebra.mp4](https://www.youtube.com/watch?v=XkY2DOUCWMU)
- [ ] [Three-dimensional linear transformations ｜ Chapter 5, Essence of linear algebra.mp4](https://www.youtube.com/watch=v=rHLEWRxRGiM)
- [ ] [The determinant ｜ Chapter 6, Essence of linear algebra.mp4](https://www.youtube.com/watch?v=Ip3X9LOh2ZI)
- [ ] [Inverse matrices, column space and null space ｜ Chapter 7, Essence of linear algebra.mp4](https://www.youtube.com/watch?v=uQhTuRlWMxw)
- [ ] [Nonsquare matrices as transformations between dimensions ｜ Chapter 8, Essence of linear algebra.mp4](https://www.youtube.com/watch=v=v8VSDg_WQlA)
- [ ] [Dot products and duality ｜ Chapter 9, Essence of linear algebra.mp4](https://www.youtube.com/watch=v=LyGKycYT2vQ)
- [ ] [Cross products ｜ Chapter 10, Essence of linear algebra.mp4](https://www.youtube.com/watch?v=eu6i7WJeinw)
- [ ] [Cross products in the light of linear transformations ｜ Chapter 11, Essence of linear algebra.mp4](https://www.youtube.com/watch=v=BaM7OCEm3G0)
- [ ] [Cramer's rule, explained geometrically ｜ Chapter 12, Essence of linear algebra.mp4](https://www.youtube.com/watch?v=jBsC34PxzoM)
- [ ] [Change of basis ｜ Chapter 13, Essence of linear algebra.mp4](https://www.youtube.com/watch=v=P2LTAUO1TdA)
- [ ] [Eigenvectors and eigenvalues ｜ Chapter 14, Essence of linear algebra.mp4](https://www.youtube.com/watch?v=PFDu9oVAE-g)
- [ ] [A quick trick for computing eigenvalues ｜ Chapter 15, Essence of linear algebra.mp4](https://www.youtube.com/watch=v=e50Bj7jn9IQ)
- [ ] [Abstract vector spaces ｜ Chapter 16, Essence of linear algebra.mp4](https://www.youtube.com/watch?v=TgKwz5Ikpc8)

## Week 3
### 01 - Limits and derivatives
Playlist: [3Blue1Brown Essence of calculus](https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr)
- [ ] [Introduction to limits # Limits # Differential Calculus # Khan Academy.mp4](https://www.youtube.com/watch?v=WUvTyaaNkzM)
- [ ] [The essence of calculus.mp4](https://www.youtube.com/watch?v=WUvTyaaNkzM)
- [ ] [The paradox of the derivative ｜ Chapter 2, Essence of calculus.mp4](https://www.youtube.com/watch=v=9vKqVkMQHKk)
- [ ] [Derivative formulas through geometry ｜ Chapter 3, Essence of calculus.mp4](https://www.youtube.com/watch?v=S0_qX4VJhMQ)
- [ ] [Visualizing the chain rule and product rule ｜ Chapter 4, Essence of calculus.mp4](https://www.youtube.com/watch?v=YG15m2VwSjA)
- [ ] [What's so special about Euler's number e？ ｜ Chapter 5, Essence of calculus.mp4](https://www.youtube.com/watch?v=m2MIpDrF7Es)
- [ ] [Implicit differentiation, what's going on here？ ｜ Chapter 6, Essence of calculus.mp4](https://www.youtube.com/watch?v=qb40J4N1fa4)
- [ ] [Limits, L'Hôpital's rule, and epsilon delta definitions ｜ Chapter 7, Essence of calculus.mp4](https://www.youtube.com/watch?v=kfF40MiS7zA)

### 02 - Derivative applications
Playlist: [Professor Leonard Calculus 1](https://www.youtube.com/playlist?list=PLF797E961509B4EB5)
- [ ] [Calculus 1 Lecture 2.5#   Finding Derivatives of Trigonometric Functions.mp4](https://www.youtube.com/watch?v=fYyARMqiaag)
- [ ] [Calculus 1 Lecture 3.1#  Increasing-Decreasing and Concavity of Functions.mp4](https://www.youtube.com/watch?v=1EGFSefe5II)
- [ ] [Calculus 1 Lecture 3.4#  The Second Derivative Test for Concavity of Functions.mp4](https://www.youtube.com/watch=v=SzLF-wLZF_I)
- [ ] [Calculus 1 Lecture 3.7#  Optimization; Max-Min Application Problems.mp4](https://www.youtube.com/watch?v=f-_UsIP5jyA)
- [ ] [Calculus 1 Lecture 4.3#  Area Under a Curve, Limit Approach, Riemann Sums.mp4](https://www.youtube.com/watch?v=54_XRjHhZzI)

### 03 - Integrals
Playlist: [The Organic Chemistry Tutor New Calculus Video Playlist](https://www.youtube.com/playlist?list=PL0o_zxa4K1BWYThyV4T2Allw6zY0jEumv)
- [ ] [Natural Logarithms.mp4](https://www.youtube.com/watch?v=GiCojsAWRj0)
- [ ] [Solving Exponential Equations.mp4](https://www.youtube.com/watch?v=OGeCocRTju8)
- [ ] [Solving Logarithmic Equations.mp4](https://www.youtube.com/watch?v=1xATmTI-YY8)
- [ ] [Limits.mp4](https://www.youtube.com/watch?v=Mxe2lX1htNk)
- [ ] [Evaluating Limits With Fractions and Square Roots.mp4](https://www.youtube.com/watch?v=KirGQOwjBVI)
- [ ] [How To Evaluate Limits of Radical Functions # Calculus.mp4](https://www.youtube.com/watch?v=OYOXMyFKotc)
- [ ] [Limits and Absolute Value.mp4](https://www.youtube.com/watch?v=EZeQxYg0zgg)
- [ ] [Limits of Exponential Functions # Calculus.mp4](https://www.youtube.com/watch?v=fKyBOLsqRlo)
- [ ] [Limits of Trigonometric Functions.mp4](https://www.youtube.com/watch?v=BtcKotD6Ni8)
- [ ] [Infinite Limits and Vertical Asymptotes.mp4](https://www.youtube.com/watch?v=ld4UD98yHio)
- [ ] [How To Find The Limit At Infinity.mp4](https://www.youtube.com/watch?v=TJNonQWYjkI)
- [ ] [Limits of Inverse Trigonometric Functions # Calculus.mp4](https://www.youtube.com/watch?v=Uzw9tsGq2Pw)
- [ ] [Limit Formulas - Calculus 1.mp4](https://www.youtube.com/watch?v=a5x4lwnvHM0)
- [ ] [Limits at Infinity With Radicals & Fractional Exponents.mp4](https://www.youtube.com/watch?v=8t9_IXFzH_M)
- [ ] [Limits at Infinity & Horizontal Asymptotes.mp4](https://www.youtube.com/watch?v=6J4EgWY3ViI)
- [ ] [Limits and Logarithms.mp4](https://www.youtube.com/watch?v=4vBPVWtE77w)
- [ ] [Logarithms - e - Euler's Number.mp4](https://www.youtube.com/watch?v=4vBPVWtE77w)
- [ ] [Squeeze Theorem.mp4](https://www.youtube.com/watch?v=KfZnLGJXLHM)
- [ ] [Greatest Integer Function With Limits & Graphs.mp4](https://www.youtube.com/watch?v=4vBPVWtE77w)
- [ ] [Limits of Logarithmic Functions # Calculus.mp4](https://www.youtube.com/watch?v=4vBPVWtE77w)
- [ ] [Limits of Natural Logarithmic Functions - Calculus.mp4](https://www.youtube.com/watch?v=4vBPVWtE77w)
- [ ] [Intermediate Value Theorem.mp4](https://www.youtube.com/watch?v=4vBPVWtE77w)
- [ ] [Continuity Basic Introduction, Point, Infinite, & Jump Discontinuity, Removable & Nonremovable.mp4](https://www.youtube.com/watch?v=ooTWZSh5XYc)
- [ ] [Piecewise Functions - Limits and Continuity # Calculus.mp4](https://www.youtube.com/watch?v=0nEubNIQE20)
- [ ] [3 Step Continuity Test, Discontinuity, Piecewise Functions & Limits # Calculus.mp4](https://www.youtube.com/watch?v=WT7oxiiFYt8)
- [ ] [Continuity and Differentiability.mp4](https://www.youtube.com/watch?v=kfF40MiS7zA)
- [ ] [How To Find The Limit of a Composite Function Given Two Graphs.mp4](https://www.youtube.com/watch=v=ooTWZSh5XYc)
- [ ] [How To Find The Limit of a Composite Function - Calculus.mp4](https://www.youtube.com/watch?v=ooTWZSh5XYc)
- [ ] [Limits and Continuity.mp4](https://www.youtube.com/watch=v=WT7oxiiFYt8)
- [ ] [The Power Rule For Derivatives.mp4](https://www.youtube.com/watch?v=xxMAmOAsnP0)
- [ ] [The Constant Multiple Rule For Derivatives.mp4](https://www.youtube.com/watch?v=6VJyfIapxoY)
- [ ] [Derivatives of Polynomial Functions # Calculus.mp4](https://www.youtube.com/watch?v=xxMAmOAsnP0)
- [ ] [Definition of the Derivative.mp4](https://www.youtube.com/watch?v=-aTLjoDT1GQ)
- [ ] [The Constant Rule For Derivatives.mp4](https://www.youtube.com/watch?v=6VJyfIapxoY)
- [ ] [Derivatives of Trigonometric Functions.mp4](https://www.youtube.com/watch?v=9BkR5L8g1ls)
- [ ] [Derivative of Sine and Cosine Functions # Calculus.mp4](https://www.youtube.com/watch?v=vD9FSUzrHbk)
- [ ] [Alternate Form of The Limit Definition of the Derivative - Calculus.mp4](https://www.youtube.com/watch?v=6o7b9yyhH7k)
- [ ] [Limits and Derivatives.mp4](https://www.youtube.com/watch=v=6o7b9yyhH7k)
- [ ] [How To Find The Equation of The Tangent Line With Derivatives.mp4](https://www.youtube.com/watch=v=WIUZmbtAyR8)
- [ ] [How To Find The Equation of a Tangent Line Using Derivatives - Calculus 1.mp4](https://www.youtube.com/watch?v=WIUZmbtAyR8)
- [ ] [How to Find The Point Where The Graph has a  Horizontal Tangent Lines Using Derivatives.mp4](https://www.youtube.com/watch=v=WIUZmbtAyR8)
- [ ] [How To Find The Equation of the Normal Line.mp4](https://www.youtube.com/watch?v=WIUZmbtAyR8)
- [ ] [How To Find The Equation of a Secant Line.mp4](https://www.youtube.com/watch?v=WIUZmbtAyR8)
- [ ] [Instantaneous Rate of Change.mp4](https://www.youtube.com/watch=v=WIUZmbtAyR8)
- [ ] [Average Velocity and Instantaneous Velocity.mp4](https://www.youtube.com/watch?v=WIUZmbtAyR8)
- [ ] [Derivatives of Rational Functions.mp4](https://www.youtube.com/watch=v=WIUZmbtAyR8)
- [ ] [Derivatives of Radical Functions.mp4](https://www.youtube.com/watch?v=WIUZmbtAyR8)
- [ ] [How To Find The Derivative of a Fraction - Calculus.mp4](https://www.youtube.com/watch?v=WIUZmbtAyR8)
- [ ] [Product Rule For Derivatives.mp4](https://www.youtube.com/watch=v=WIUZmbtAyR8)
- [ ] [Product Rule With 3 Functions - Derivatives # Calculus.mp4](https://www.youtube.com/watch=v=WIUZmbtAyR8)
- [ ] [Product Rule With 4 Functions - Derivatives # Calculus.mp4](https://www.youtube.com/watch?v=WIUZmbtAyR8)
- [ ] [Quotient Rule For Derivatives.mp4](https://www.youtube.com/watch=v=WIUZmbtAyR8)
- [ ] [The Reciprocal Rule and The Quotient Rule - Derivative Calculus.mp4](https://www.youtube.com/watch?v=WIUZmbtAyR8)
- [ ] [Chain Rule For Finding Derivatives.mp4](https://www.youtube.com/watch=v=WIUZmbtAyR8)
- [ ] [How To Find The Derivative of Sin^2(x), Sin(2x), Sin^2(2x), Tan3x, & Cos4x.mp4](https://www.youtube.com/watch=v=WIUZmbtAyR8)
- [ ] [Calculus - Chain Rule - Derivatives.mp4](https://www.youtube.com/watch=v=WIUZmbtAyR8)
- [ ] [Find The Derivative Using The Chain Rule.mp4](https://www.youtube.com/watch?v=WIUZmbtAyR8)
- [ ] [Simplifying Derivatives.mp4](https://www.youtube.com/watch=v=WIUZmbtAyR8)
- [ ] [Higher Order Derivatives.mp4](https://www.youtube.com/watch?v=WIUZmbtAyR8)
- [ ] [Implicit Differentiation.mp4](https://www.youtube.com/watch=v=WIUZmbtAyR8)
- [ ] [Derivatives of Inverse Trigonometric Functions.mp4](https://www.youtube.com/watch=v=WIUZmbtAyR8)
- [ ] [Derivatives of Exponential Functions.mp4](https://www.youtube.com/watch?v=WIUZmbtAyR8)
- [ ] [Derivative of Logarithmic Functions.mp4](https://www.youtube.com/watch?v=WIUZmbtAyR8)
- [ ] [Introduction to Logarithmic Differentiation.mp4](https://www.youtube.com/watch=v=WIUZmbtAyR8)
- [ ] [Logarithmic Differentiation Formula - Calculus.mp4](https://www.youtube.com/watch=v=WIUZmbtAyR8)
- [ ] [Finding Derivatives Using Logarithms - Differential Calculus.mp4](https://www.youtube.com/watch?v=WIUZmbtAyR8)
- [ ] [Derivatives of Inverse Functions # Calculus.mp4](https://www.youtube.com/watch=v=WIUZmbtAyR8)
- [ ] [Basic Differentiation Rules For Derivatives.mp4](https://www.youtube.com/watch?v=WIUZmbtAyR8)
- [ ] [Differentiation Formulas - Notes.mp4](https://www.youtube.com/watch=v=WIUZmbtAyR8)
- [ ] [Geometric Series and Geometric Sequences - Basic Introduction.mp4](https://www.youtube.com/watch?v=gqryqIlKnms)
- [ ] [How To Find The Sum of a Geometric Series.mp4](https://www.youtube.com/watch?v=1k4kv2v8j5E)
- [ ] [Finding The Sum of a Finite Geometric Series.mp4](https://www.youtube.com/watch?v=1k4kv2v8j5E)
- [ ] [Finding The Sum of an Infinite Geometric Series.mp4](https://www.youtube.com/watch?v=1k4kv2v8j5E)
- [ ] [Convergence and Divergence - Introduction to Series.mp4](https://www.youtube.com/watch=v=1k4kv2v8j5E)
- [ ] [Divergence Test For Series - Calculus 2.mp4](https://www.youtube.com/watch?v=1k4kv2v8j5E)
- [ ] [Harmonic Series.mp4](https://www.youtube.com/watch?v=1k4kv2v8j5E)
- [ ] [Telescoping Series.mp4](https://www.youtube.com/watch?v=1k4kv2v8j5E)
- [ ] [Calculus 2 - Integral Test For Convergence and Divergence of Series.mp4](https://www.youtube.com/watch=v=1k4kv2v8j5E)
- [ ] [Remainder Estimate For The Integral Test.mp4](https://www.youtube.com/watch=v=1k4kv2v8j5E)
- [ ] [P-series.mp4](https://www.youtube.com/watch?v=1k4kv2v8j5E)
- [ ] [Direct Comparison Test - Calculus 2.mp4](https://www.youtube.com/watch?v=1k4kv2v8j5E)
- [ ] [Limit Comparison Test.mp4](https://www.youtube.com/watch=v=1k4kv2v8j5E)
- [ ] [Alternating Series Test.mp4](https://www.youtube.com/watch=v=1k4kv2v8j5E)
- [ ] [Alternate Series Estimation Theorem.mp4](https://www.youtube.com/watch?v=1k4kv2v8j5E)
- [ ] [Absolute Convergence, Conditional Convergence, and Divergence.mp4](https://www.youtube.com/watch=v=FPK6LO1iiXc)
- [ ] [Ratio Test.mp4](https://www.youtube.com/watch=v=UjYnVYBc5CM)
- [ ] [Root Test.mp4](https://www.youtube.com/watch?v=ahf0eXOll1M)
- [ ] [Calculus 2 - Geometric Series, P-Series, Ratio Test, Root Test, Alternating Series, Integral Test.mp4](https://www.youtube.com/watch=v=0YeON4p0ogw)
- [ ] [Taylor Polynomials & Maclaurin Polynomials With Approximations.mp4](https://www.youtube.com/watch?v=1k4kv2v8j5E)
- [ ] [Taylor's Remainder Theorem.mp4](https://www.youtube.com/watch=v=1k4kv2v8j5E)
- [ ] [Power Series - Finding The Radius & Interval of Convergence - Calculus 2.mp4](https://www.youtube.com/watch?v=1k4kv2v8j5E)
- [ ] [Power Series - Differentiation and Integration - Calculus 2.mp4](https://www.youtube.com/watch?v=1k4kv2v8j5E)
- [ ] [Power Series - Representation of Functions - Calculus 2.mp4](https://www.youtube.com/watch?v=1k4kv2v8j5E)
- [ ] [Finding Power Series By Differentiation.mp4](https://www.youtube.com/watch=v=1k4kv2v8j5E)
- [ ] [Power Series Representation By Integration - Calculus 2.mp4](https://www.youtube.com/watch?v=1k4kv2v8j5E)
- [ ] [Power Series Representation With Natural Logarithms - Calculus 2.mp4](https://www.youtube.com/watch?v=1k4kv2v8j5E)
- [ ] [Taylor Series and Maclaurin Series - Calculus 2.mp4](https://www.youtube.com/watch?v=1k4kv2v8j5E)
- [ ] [Binomial Series.mp4](https://www.youtube.com/watch?v=1k4kv2v8j5E)

### 04 - Series
Playlist: [3Blue1Brown Essence of calculus](https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr)
- [ ] [Taylor series # Chapter 11, Essence of calculus.mp4](https://www.youtube.com/watch?v=3d6DsjIBzJ4)

## Week 4
### 01 - Partial derivatives and gradients
Playlist: [Khan Academy Partial derivatives gradient divergence curl multivariable calculus](https://www.youtube.com/playlist?list=PLSQl0a2vh4HCHBrSa1YErcRXpiz_BQRDS)
- [ ] [Partial derivatives 2 # Multivariable Calculus # Khan Academy.mp4](https://www.youtube.com/watch?v=-u0mqFqpMNY)
- [ ] [Partial derivatives # Multivariable Calculus # Khan Academy.mp4](https://www.youtube.com/watch?v=1CMDS4-PKKQ)
- [ ] [Gradient of a scalar field # Multivariable Calculus # Khan Academy.mp4](https://www.youtube.com/watch?v=JAXyLhvZ-Vg)
- [ ] [Gradient 1 # Partial derivatives, gradient, divergence, curl # Multivariable Calculus # Khan Academy.mp4](https://www.youtube.com/watch?v=Mt4dpGFVsYc)

### 02 - Multiple integrals
Playlist: [Khan Academy Double Triple Integrals](https://www.youtube.com/playlist?list=PLSQl0a2vh4HB3NJGQ_EYP1qFEVdN9Ro68)
- [ ] [Double integral 1 # Double and triple integrals # Multivariable Calculus # Khan Academy.mp4](https://www.youtube.com/watch?v=0pv0QtOi5l8)
- [ ] [Double integrals 2 # Double and triple integrals # Multivariable Calculus # Khan Academy.mp4](https://www.youtube.com/watch?v=85zGYB-34jQ)
- [ ] [Double integrals 3 # Double and triple integrals # Multivariable Calculus # Khan Academy.mp4](https://www.youtube.com/watch?v=TdLD2Zh-nUQ)
- [ ] [Double integrals 4 # Double and triple integrals # Multivariable Calculus # Khan Academy.mp4](https://www.youtube.com/watch?v=ZN2PfqZ4ihM)
- [ ] [Double integrals 5 # Double and triple integrals # Multivariable Calculus # Khan Academy.mp4](https://www.youtube.com/watch?v=hrIPO8mQqtw)
- [ ] [Double integrals 6 # Double and triple integrals # Multivariable Calculus # Khan Academy.mp4](https://www.youtube.com/watch?v=twT-WZChfZ8)

### 03 - Probability
Playlist: [Khan Academy Probability](https://www.youtube.com/playlist?list=PLC58778F28211FA19)
- [ ] [Probability explained # Independent and dependent events # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch?v=uzkc-qNVoOk)
- [ ] [Probability with playing cards and Venn diagrams # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch?v=obZzOq_wSCg)
- [ ] [Addition rule for probability # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch?v=QE2uR6Z-NcU)
- [ ] [Finding probability example 2 # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch?v=mLE-SlOZToc)
- [ ] [Compound probability of independent events # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch?v=xSc4oLA9e8o)
- [ ] [Coin flipping probability # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch?v=mkyZ45KQYi4)
- [ ] [Probability without equally likely events # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch?v=RI874OSJp1U)
- [ ] [Getting exactly two heads (combinatorics) # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch?v=8TIben0bJpU)
- [ ] [Exactly three heads in five flips # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch?v=udG9KhNMKJw)
- [ ] [Frequency stability property short film # Computer Science # Khan Academy.mp4](https://www.youtube.com/watch=v=vVXbgbMp0oY)
- [ ] [Probability (part 2).mp4](https://www.youtube.com/watch?v=AOsWph2FNLw)
- [ ] [Probability (part 3).mp4](https://www.youtube.com/watch=v=6E_NVnboMB8)
- [ ] [Probability (part 4).mp4](https://www.youtube.com/watch?v=wBDOCvHYckE)
- [ ] [Probability (part 5).mp4](https://www.youtube.com/watch=v=W581OBM9rAY)
- [ ] [Probability (part 6).mp4](https://www.youtube.com/watch=v=2UjLF6y2Pek)
- [ ] [Dependent probability example # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch?v=xPUm5SUVzTE)
- [ ] [Dependent probability example 2 # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch=v=7BkcNLOf56w)
- [ ] [Probability (part 7).mp4](https://www.youtube.com/watch=v=BLcgeLALLnc)
- [ ] [Probability (part 8).mp4](https://www.youtube.com/watch=v=VVr8snbaxZg)
- [ ] [Permutations.mp4](https://www.youtube.com/watch?v=XqQTXW7XfYA)
- [ ] [Combinations.mp4](https://www.youtube.com/watch=v=bCxMhncR7PU)
- [ ] [Probability using combinations # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch?v=Xqfcy1rqMbI)
- [ ] [Probability and combinations (part 2) # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch=v=W7DmsJKLoxc)
- [ ] [Conditional probability and combinations # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch?v=xw6utjoyMi4)
- [ ] [Birthday probability problem # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch?v=9G0w61pZPig)
- [ ] [Introduction to Random Variables.mp4](https://www.youtube.com/watch?v=IYdiKeQ9xEI)
- [ ] [Probability density functions # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch=v=Fvi9A_tEmXQ)
- [ ] [Binomial Distribution 1.mp4](https://www.youtube.com/watch=v=O12yTz_8EOw)
- [ ] [Binomial Distribution 2.mp4](https://www.youtube.com/watch=v=FI8xtVaI068)
- [ ] [Binomial Distribution 3.mp4](https://www.youtube.com/watch=v=vKNpQ_KTXvE)
- [ ] [Binomial Distribution 4.mp4](https://www.youtube.com/watch=v=H0ZgOGWUcJw)
- [ ] [Expected Value# E(X).mp4](https://www.youtube.com/watch=v=j__Kredt7vY)
- [ ] [Expected value of binomial distribution # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch=v=SqcxYnNlI3Y)
- [ ] [Poisson process 1 # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch=v=3z-M6sbGIZ0)

### 04 - Basic statistics
Playlist: [Khan Academy Statistics](https://www.youtube.com/playlist?list=PL1328115D3D8A2566)
- [ ] [Statistics# Sample vs. Population Mean.mp4](https://www.youtube.com/watch?v=yx5KZi5QArQ)
- [ ] [Statistics# Variance of a population # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch?v=sHRB7Lz6dAA)
- [ ] [Statistics# Sample variance # Descriptive statistics # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch?v=9ltMoF3nfWk)
- [ ] [Statistics# Standard deviation # Descriptive statistics # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch?v=09kiX3p5VZg)
- [ ] [Statistics# Alternate variance formulas # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch=v=paQ2gcn1ego)
- [ ] [Introduction to Random Variables.mp4](https://www.youtube.com/watch=v=3v9w79NhsfI)
- [ ] [Probability density functions # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch=v=Fvi9A_tEmXQ)
- [ ] [Binomial Distribution 1.mp4](https://www.youtube.com/watch=v=8idr1WZ1A7Q)
- [ ] [Binomial Distribution 2.mp4](https://www.youtube.com/watch?v=gH2fWvXR9n4)
- [ ] [Binomial Distribution 3.mp4](https://www.youtube.com/watch=v=3pwDSC5uYws)
- [ ] [Binomial Distribution 4.mp4](https://www.youtube.com/watch=v=syijLJ3oQzU)
- [ ] [Expected Value# E(X).mp4](https://www.youtube.com/watch?v=j-rDJjrL7zM)
- [ ] [Expected value of binomial distribution # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch=v=KMPrzZ4L0G8)
- [ ] [Poisson process 1 # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch=v=3z-M6sbGIZ0)
- [ ] [Poisson process 2 # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch=v=Jkr4FSrNEVY)
- [ ] [Law of large numbers # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch?v=VpuN8vCQ--M)
- [ ] [Normal distribution excel exercise # Probability and Statistics # Khan Academy.mp4](https://www.youtube.com/watch?v=JNm3M9cqWyc)

### 05 - Optimization techniques
- [ ] [Gradient descent, how neural networks learn # Deep Learning Chapter 2.mp4](https://www.youtube.com/watch?v=IHZwWFHWa-w)

### 06 - Bayes theorem
- [ ] [Bayes theorem, the geometry of changing beliefs.mp4](https://www.youtube.com/watch?v=HZGCoVF3YvM)
